name: Terraform-docs Auto Update

on:
  push:
    branches: [ 'master' ]
    paths-ignore: 
      - '.github/*'
      - '.gitignore'
      - '.gitattributes'

jobs:
  workflow-calling:
    uses: BancoArbi/github-terraform-workflows/.github/workflows/terraform-docs.yml@v0.0.4
